---
title: "RED"
author: "Miguel Morin"
date: "16/05/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = 2)
options(error=function () {
  traceback(2)
})

```



# Install and load required packages
```{r}
package_list <- c("digest", "devtools")

for (p in package_list) {
  if (! p %in% installed.packages()) {
    install.packages(p, repos = "https://cran.ma.imperial.ac.uk")
  }
}

# TODO: remove this
setwd("/Users/mmorin/Computer_adoption_2k/RED/")
library("devtools")
devtools::install()

# Load data after installing
library("RED")

```

# Get data and verify hashes

Download the data from [FRED](https://fred.stlouisfed.org/) for [payroll employment](https://fred.stlouisfed.org/series/PAYEMS) and [GDP](https://fred.stlouisfed.org/series/GDPC1), and save to folder "data/".

Verify that the hashes coincide to prevent results changing under my feet because of changes in data.

```{r}

# copy-paste business cycle dates from http://www.nber.org/cycles.html :
peaks <- "May 1937(II)
February 1945(I)
November 1948(IV)
July 1953(II)
August 1957(III)
April 1960(II)
December 1969(IV)
November 1973(IV)
January 1980(I)
July 1981(III)
July 1990(III)
March 2001(I)
December 2007 (IV)"

troughs <- "June 1938 (II)
October 1945 (IV)
October 1949 (IV)
May 1954 (II)
April 1958 (II)
February 1961 (I)
November 1970 (IV)
March 1975 (I)
July 1980 (III)
November 1982 (IV)
March 1991(I)
November 2001 (IV)
June 2009 (II)"

# Location of all .CSV files
data_folder <- "data"

# Make a list of hashes
hashes <- list(GDPC1.csv = "64ab3a933af2af2155927d6176ffb082",
               PAYEMS.csv = "79eefe7841a9efa8ff3cdcc1f72bd73f",
               peaks = "1beeff4186d1df38fde04643d93410be",
               troughs = "596269d021d7c6eeb3b496c31b315fe5")

# Verify hashes
for (key in names(hashes)) {
  hash <- digest::digest(file.path(data_folder, key),
                        file = grepl(".+\\..+", key),
                        algo = "md5")
  stopifnot(hashes[[key]] == hash)
}
```


# Figure 1: recovery of payroll employment

```{r}
# Convert business cycle dates to dates
cycles_df <- nber_cycles_2_df(peaks = peaks, troughs = troughs)
```


Same with women and men, and blacks, etc.
